### ISSUE TITLE
Make an include guard unique

### ISSUE THREAD

**Issue by elfring** [dvhart/librtpi#12]
I find that an include guard like “[`RPTI_H`](https://github.com/dvhart/librtpi/blob/4e22869e124af5bac90d18aa7c91ac1aba7ca5df/rtpi.h#L4 "Update candidate")” can be too short for the safe reuse of your header file (when it belongs to an application programming interface).

**Comment by dvhart** [comment]
Well, it seems I was sloppy in my %s replace. Sigh. As that should have been RTPI_H. Given the limited use of this library in real-time applications, a collision seems highly unlikely. However, a change is required to correct my mistake. If you would like to submit a PR to something you find suitable, please do so.

**Comment by elfring** [comment]
Would an include guard like “`RTPI_H_827b0e37a3a1431f8ad00d9fc0ebf176`” be unique enough?

**Comment by dvhart** [comment]
I'm willing to revisit this if it becomes an issue, I don't feel we need to resort to global uniqueness for a header guard.

**Comment by elfring** [comment]
Would you prefer an other name pattern (besides a simple fix for a typo) than appending [a kind of UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier "Description for the usage of universally unique identifiers")?
