### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [dvhart/librtpi#9]
I would like to point out that an identifier like “[`_RTPI_H`](https://github.com/dvhart/librtpi/blob/9817e63802641b868307b8b20f8f0171eb81281d/rtpi.h#L4 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by dvhart** [comment]
Thank you for reporting the issue along with the justification. Would you care to submit a PR addressing it?

**Comment by elfring** [comment]
Would [the simple renaming of the affected identifier(s)](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") be easier for you?

**Comment by dvhart** [comment]
From my reading of the links you've shared, it seems simply removing the leading _ from the header guards would resolve the issue. Agreed?

**Comment by elfring** [comment]
Thanks for [your adjustment of affected include guards](https://github.com/dvhart/librtpi/pull/10/commits/4e22869e124af5bac90d18aa7c91ac1aba7ca5df "Fix reserved identifier violation in header guards").
